using UnityEngine;

namespace CustomUtility.ConsoleUtility
{
    [CreateAssetMenu(fileName = "ConsoleSettings", menuName = "CustomUtility/Console/ConsoleSettings")]
    public class ConsoleSettings : ScriptableObject
    {
        public enum ExecutionMode
        {
            Reflection,
            AutoGenerated
        }
        
        public ExecutionMode Mode = ExecutionMode.Reflection;
    }
}