//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/CustomUtility/ConsoleUtility/CustomConsole_ActionMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CustomUtility.ConsoleUtility.Input
{
    public partial class @CustomConsole_ActionMap: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @CustomConsole_ActionMap()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""CustomConsole_ActionMap"",
    ""maps"": [
        {
            ""name"": ""CustomConsole"",
            ""id"": ""3d2d053a-d8da-4d88-b051-dd0509614eef"",
            ""actions"": [
                {
                    ""name"": ""ToggleWindow"",
                    ""type"": ""Button"",
                    ""id"": ""b9a570ee-4916-4138-916a-a4b831e96565"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09a7df99-5aff-451a-89b6-c18cef088538"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWindow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // CustomConsole
            m_CustomConsole = asset.FindActionMap("CustomConsole", throwIfNotFound: true);
            m_CustomConsole_ToggleWindow = m_CustomConsole.FindAction("ToggleWindow", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // CustomConsole
        private readonly InputActionMap m_CustomConsole;
        private List<ICustomConsoleActions> m_CustomConsoleActionsCallbackInterfaces = new List<ICustomConsoleActions>();
        private readonly InputAction m_CustomConsole_ToggleWindow;
        public struct CustomConsoleActions
        {
            private @CustomConsole_ActionMap m_Wrapper;
            public CustomConsoleActions(@CustomConsole_ActionMap wrapper) { m_Wrapper = wrapper; }
            public InputAction @ToggleWindow => m_Wrapper.m_CustomConsole_ToggleWindow;
            public InputActionMap Get() { return m_Wrapper.m_CustomConsole; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CustomConsoleActions set) { return set.Get(); }
            public void AddCallbacks(ICustomConsoleActions instance)
            {
                if (instance == null || m_Wrapper.m_CustomConsoleActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CustomConsoleActionsCallbackInterfaces.Add(instance);
                @ToggleWindow.started += instance.OnToggleWindow;
                @ToggleWindow.performed += instance.OnToggleWindow;
                @ToggleWindow.canceled += instance.OnToggleWindow;
            }

            private void UnregisterCallbacks(ICustomConsoleActions instance)
            {
                @ToggleWindow.started -= instance.OnToggleWindow;
                @ToggleWindow.performed -= instance.OnToggleWindow;
                @ToggleWindow.canceled -= instance.OnToggleWindow;
            }

            public void RemoveCallbacks(ICustomConsoleActions instance)
            {
                if (m_Wrapper.m_CustomConsoleActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICustomConsoleActions instance)
            {
                foreach (var item in m_Wrapper.m_CustomConsoleActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CustomConsoleActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CustomConsoleActions @CustomConsole => new CustomConsoleActions(this);
        public interface ICustomConsoleActions
        {
            void OnToggleWindow(InputAction.CallbackContext context);
        }
    }
}
